# For more information on GitHub Actions, refer to https://github.com/features/actions
# For a complete CI/CD sample to get started with GitHub Action workflows for Desktop Applications,
# refer to https://github.com/microsoft/github-actions-for-desktop-apps
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
# https://www.meziantou.net/publishing-a-nuget-package-following-best-practices-using-github.htm

name: Gated Check-in

on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4

    - name: Setup Wix
      run: dotnet tool install --global wix

    - name: Restore packages
      run: dotnet restore

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test --logger trx --results-directory "TestResults"