# For more information on GitHub Actions, refer to https://github.com/features/actions
# For a complete CI/CD sample to get started with GitHub Action workflows for Desktop Applications,
# refer to https://github.com/microsoft/github-actions-for-desktop-apps
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
# https://www.meziantou.net/publishing-a-nuget-package-following-best-practices-using-github.htm

name: Gated Check-in

on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  pull_request:
    branches: [ "master" ]

env:
  NUGET_USER: el.barrent@gmail.com
  NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    permissions:
      packages: read
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4

    - name: Setup Wix
      run: dotnet tool install --global wix

    - name: 'Add source'
      run: dotnet nuget add source --username ${{ env.NUGET_USER }} --password ${{ env.NUGET_AUTH_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Barrent/index.json"

    - name: Restore packages
      run: dotnet restore
      working-directory: Source      

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: dotnet build --no-restore
      working-directory: Source

    - name: Run tests
      run: dotnet test --logger trx --results-directory "TestResults"
      working-directory: Source